name: sputnik_location
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^5.0.0
  test: ^1.24.0
